layout_spectrum: 0.06415647
color:
  saturation: 0.2138458
  lightness: 0.7004309
  brandStrength: 0.476292
  brandColors:
    - '#E1DBDD'
    - '#808B01'
    - '#442417'
    - '#FF2C00'
    - '#DC9768'
  rhythmicContrast: 0.4190459
typography_spectrum: 0.898748
name: RuthviP
