collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.5595745
  brandStrength: 0.476292
  lightness: 0.3404255
  brandColors:
    - '#E1DBDD'
    - '#808B01'
    - '#442417'
    - '#FF2C00'
    - '#DC9768'
  rhythmicContrast: 0.5106383
typography_spectrum: 0.898748
layout_spectrum: 0.5574468
name: RuthviP
